---
title: "Visualization"
author: "Rachel Zhang (yz2334)"
date: "7/17/2020"
output: pdf_document
---

# Newest ROH

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r loadsession}
load("~/Documents/Research/MLJournalPaper/Data/Final Script/sessions/newestROH.RData")
```

Only plot Regression, SVR, additive pickup, and Random Forest. 

```{r MAE4}
MAE4 = MAE_ALL[-13, c(1,3,8,9)]
MAE4melt = melt(as.matrix(MAE4), varnames=c('DBA', 'Model'))
MAE4melt$DBA = factor(MAE4melt$DBA,
              levels = c(paste0('DBA', agg)))
MAE4melt$Model = factor(MAE4melt$Model,
              levels=c('apk','mpk','reg','nn','knn','wknn', 'dtree', 'rf','svr'))
```


```{r MAE4plot, fig.width=4, fig.height=6}
ggplot(MAE4melt, aes(x=DBA, y=value, group=Model, color=Model)) +
  geom_line(aes(color=Model), size=1)+
  geom_point(aes(color=Model), size=1)+
  scale_color_brewer(palette="Set2")+
  xlab('') + ylab('Mean Absolute Errors') +
  theme_minimal()+#ylim(0,15)+
  theme(axis.text.x = element_text(angle=45, vjust=0.5))
```
